import streamlit as st
st.title('Manchester City Football Club')
st.sidebar.title('Manchester City')
st.sidebar.title('Ubicacion')
st.sidebar.write('Manchester, Reino Unido')
st.text('Premier League')
st.image('city.jpg')
st.sidebar.title('Estadio')
st.sidebar.text('Etihad Stadium')
st.sidebar.title('Entrenador')
st.sidebar.text(' Pep Guardiola ')
